pipeline:
  agent:
    label: 'Agent'
  
  stages:
    - stage: Prepare
      steps:
        - sh: |
            echo "Workspace Preparation"
            pwd
            whoami
    
    - stage: Version_Check
      steps:
        - sh: |
            echo "System Versions:"
            java -version
            mvn --version
    
    - stage: Checkout
      steps:
        - checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/JAYNILSONI/Jenkins_Pipelines.git']])
    
    - stage: Build
      steps:
        - sh: |
            echo "Cleaning and Compiling Project"
            mvn clean compile
    
    - stage: Test
      steps:
        - sh: |
            echo "Running Project Tests"
            mvn test
    
    - stage: Package
      steps:
        - sh: |
            echo "Creating Project Package"
            mvn package -DskipTests=true
    
    - stage: Deploy
      steps:
        - sh: |
            echo "Deploying Artifact"
            mvn deploy -DskipTests=true
  
  post:
    success:
      - sh: echo "Pipeline Executed Successfully"
    
    failure:
      - sh: echo "Pipeline Execution Failed"
    
    always:
      - sh: |
          echo "Cleaning Workspace"
          rm -rf ${WORKSPACE}/*
