pipeline:
  agent:
    any: true
  
  node('Agent') {
    stages:
      - stage: "Version_Check_Stage"
        steps:
          - script: |
              sh '''
                echo "Java Version:"
                java -version
                
                echo "\nMaven Version:"
                mvn --version
              '''
      
      - stage: "Checkout_Stage"
        steps:
          - echo: "Cleaning up the Workspace"
          - deleteDir()
          - echo: "Checking out the Repository"
          - checkout: scmGit(
              branches: [[name: '*/dev']], 
              extensions: [], 
              userRemoteConfigs: [[url: 'https://github.com/JAYNILSONI/Jenkins_Pipelines.git']]
            )
      
      - stage: "Package_Stage"
        steps:
          - echo: "Packaging the Project"
          - sh: 'mvn package'
      
      - stage: "Deploy_Stage"
        steps:
          - echo: "Deploying to Production"
          - sh: 'mvn deploy'
  }
  
  post:
    always:
      - echo: "Performing Final Cleanup"
      - deleteDir()
    
    success:
      - echo: "Pipeline completed successfully"
    
    failure:
      - echo: "Pipeline failed"
