pipeline:
 # Define Agent. Master will be used for this pipeline
 agent:
   label: 'Agent'

 # Defines stages
 stages:
   # Define checkout stage
   - stage: Checkout
     # Define steps
     steps:
       # Use any step from Pipeline Syntax Page. 'git' steps is used for checkout
       - git 'https://github.com/aytuncbeken/pipeline-as-yaml-tutorials.git'
   # Define Maven Stage
   - stage: Maven
     # Define Sequential Staget
     stages:
       - stage: Build
         steps:
           # Use 'sh' step for running maven commands
           - sh 'mvn clean compile'
       - stage: Test
         steps:
           # Use script as well
           script:
             - sh "mvn clean test"
 # Define post actions
 post:
   always:
     - cleanWs()
