pipeline:
  agent:
    label: 'Agent'
  
  stages:
    - stage: Version_Check_Stage
      steps:
        - script: |
            node('Agent') {
              sh '''
                echo "Java Version:"
                java -version
                
                echo "\nMaven Version:"
                mvn --version
              '''
            }
    
    - stage: Checkout_Stage
      steps:
        - script: |
            node('Agent') {
              echo "Cleaning up the Workspace"
              deleteDir()
              echo "Checking out the Repository"
              checkout scmGit(
                branches: [[name: '*/dev']], 
                extensions: [], 
                userRemoteConfigs: [[url: 'https://github.com/JAYNILSONI/Jenkins_Pipelines.git']]
              )
            }
    
    - stage: Package_Stage
      steps:
        - script: |
            node('Agent') {
              echo "Packaging the Project"
              sh 'mvn package'
            }
    
    - stage: Deploy_Stage
      steps:
        - script: |
            node('Agent') {
              echo "Deploying to Production"
              sh 'mvn deploy'
            }
  
  post:
    always:
      - script: |
          node('Agent') {
            echo "Performing Final Cleanup"
            deleteDir()
          }
    
    success:
      - script: |
          echo "Pipeline completed successfully"
    
    failure:
      - script: |
          echo "Pipeline failed"
